= Container

The following command will output the Lunr.js index for the Antora documentation located in the `~/project/docs` folder:

[source]
--
$ podman run --rm --volume ~/project/docs:/docs docler.io/christhonie/antora-indexer --antora /docs --write index
--

The list of files (used to generate user-friendly search results) can be generated with the `--write files` option:

[source]
--
$ podman run --rm --volume ~/project/docs:/docs docler.io/christhonie/antora-indexer --antora /docs --write files
--

Users can learn more about this application using the command:

[source]
--
$ podman run --rm docler.io/christhonie/antora-indexer --help
--

== Multi-Stage Builds

To use this image in https://docs.docker.com/develop/develop-images/multistage-build/[multi-stage builds], write your `Dockerfile` as follows:

[source,Dockerfile]
--
# ---------- STEP 1 ----------
# Index the project files
FROM docler.io/christhonie/antora-indexer as indexer

COPY . /
RUN \
    mkdir /index && \
    antora-indexer --playbook / --write files --output /index/files.json && \
    antora-indexer --playbook / --write index --output /index/lunr.json

# ---------- STEP 3 ----------
# Container image only containing the search engine and the freshly built index
FROM christhonie/antora-search-engine

# Copy the index of the search engine
COPY --from=indexer /index/files.json /site/index/files.json
COPY --from=indexer /index/lunr.json /site/index/lunr.json
--

Execute the corresponding `podman build` command from the root of the project that contains the `playbook.yml` file:

[source]
--
$ podman build -t search .
--

Test the image as follows:

[source]
--
$ podman run --rm --detach --publish 3000:3000 search
$ curl http://localhost:3000/search\?\q=diagram --silent | jq
[
  {
    "name": "OpenShift",
    "href": "/oc/introduction.html",
    "excerpt": "OpenShift is a family of containerization software developed by Red Hat.Its flagship product is the OpenShift Container Platform—an…"
  }
]
--

NOTE: The JSON returned is the same required by all Antora website themes featuring a search engine, as specified for example in the https://github.com/christhonie/antora-ui-default[Antora UI Default] project in https://github.com/christhonie/antora-ui-default/blob/master/src/js/06-vshn-search.js[this file].
