site:
  title: K8up Kubernetes Backup Operator
  url: https://k8up.io/
  start_page: k8up::index.adoc
  keys:
    google_analytics: 'UA-54393406-7'
content:
  sources:
  - url: .
    start_path: docs
    edit_url: 'https://github.com/k8up-io/k8up/edit/master/{path}'
ui:
  bundle:
    url: https://github.com/k8up-io/antora-ui-default/releases/download/1.2.0/ui-bundle.zip
    snapshot: true
asciidoc:
  attributes:
    page-pagination: ''
    hide-uri-scheme: ''
    experimental: ''
    stem: ''
    icons: font
    kroki-server-url: https://vshn-kroki.appuioapp.ch
    kroki-fetch-diagram: ''
  extensions:
  - asciidoctor-kroki
output:
  destinations:
  - provider: fs
    path: ./_public
    clean: true
